//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using QuanLyThuVien.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class PhieuTra : BaseViewModel
    {
        private string _MaPT;
        public string MaPT { get => _MaPT; set { _MaPT = value; OnPropertyChanged(); } }


        private string _MaPM;
        public string MaPM { get => _MaPM; set { _MaPM = value; OnPropertyChanged(); } }


        private string _MaSach;
        public string MaSach { get => _MaSach; set { _MaSach = value; OnPropertyChanged(); } }

        private string _MaNV;
        public string MaNV { get => _MaNV; set { _MaNV = value; OnPropertyChanged(); } }


        private System.DateTime _NgayMuon;
        public System.DateTime NgayMuon { get => _NgayMuon; set { _NgayMuon = value; OnPropertyChanged(); } }

        private Nullable<DateTime> _NgayTra;
        public Nullable<DateTime> NgayTra { get => _NgayTra; set { _NgayTra = value; OnPropertyChanged(); } }

        private Nullable<decimal> _PhatHuHong;
        public Nullable<decimal> PhatHuHong { get => _PhatHuHong; set { _PhatHuHong = value; OnPropertyChanged(); } }


        private Nullable<decimal> _PhatQuaHan;
        public Nullable<decimal> PhatQuaHan { get => _PhatQuaHan; set { _PhatQuaHan = value; OnPropertyChanged(); } }


        private Nullable<decimal> _ThanhToan;
        public Nullable<decimal> ThanhToan { get => _ThanhToan; set { _ThanhToan = value; OnPropertyChanged(); } }


        private NhanVien _NhanVien;
        public virtual NhanVien NhanVien { get => _NhanVien; set { _NhanVien = value; OnPropertyChanged(); } }


        private PhieuMuon _PhieuMuon;
        public virtual PhieuMuon PhieuMuon { get => _PhieuMuon; set { _PhieuMuon = value; OnPropertyChanged(); } }


        private Sach _Sach;
        public virtual Sach Sach { get => _Sach; set { _Sach = value; OnPropertyChanged(); } }
    }
}
