//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using QuanLyThuVien.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class ViTri : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ViTri()
        {
            this.Saches = new HashSet<Sach>();
        }

        private string _MaVT;
        public string MaVT { get => _MaVT; set { _MaVT = value; OnPropertyChanged(); } }


        private string _TenKhu;
        public string TenKhu { get => _TenKhu; set { _TenKhu = value; OnPropertyChanged(); } }


        private string _TenKe;
        public string TenKe { get => _TenKe; set { _TenKe = value; OnPropertyChanged(); } }


        private string _TenNgan;
        public string TenNgan { get => _TenNgan; set { _TenNgan = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
